<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP-TZD-0X118172" failures="3" tests="7" name="Test" time="0.099" errors="0" timestamp="2024-10-16T19:13:43 IST">
  <testcase classname="testNGExample.AmazonTest_Retry" name="login" time="0.005"/>
  <testcase classname="testNGExample.AmazonTest_Retry" name="addItem" time="0.001"/>
  <testcase classname="testNGExample.AmazonTest_Retry" name="payment" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNGExample.AmazonTest_Retry.payment(AmazonTest_Retry.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- payment -->
  <testcase classname="testNGExample.AmazonTest_Retry" name="updateOrder" time="0.003">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNGExample.AmazonTest_Retry.updateOrder(AmazonTest_Retry.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- updateOrder -->
  <testcase classname="testNGExample.AmazonTest_Retry" name="logout" time="0.0"/>
  <testcase classname="actoinExample.AmazonPaymetModule" name="verifyPaymentModule" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at actoinExample.AmazonPaymetModule.verifyPaymentModule(AmazonPaymetModule.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyPaymentModule -->
  <testcase classname="actoinExample.AmazonPaymetModule" name="verifyUPIPaymentModule" time="0.002"/>
</testsuite> <!-- Test -->
